### ISSUE TITLE
Wiki Page PDF exports don't display the diagrams

### ISSUE THREAD

**Issue by p-collins** [redmica/redmica_ui_extension#47]
Thank you for this plugin allowing the implementation of Mermaid. 

I would just like to ask if you think it would be possible to have the wiki page PDF render include the diagrams?

**Comment by ishikawa999** [comment]
@p-collins 

Thank you for using this plugin.
I have checked and it seems that it is difficult to output a mermaid diagram with the Redmine pdf export. I apologize that I could not be of help.

It may be possible to use the PDF export functionality that your browser has as an alternative.
